basePath: /
definitions:
  internal_handler.Attendee:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  internal_handler.CheckoutInput:
    properties:
      attendees:
        items:
          $ref: '#/definitions/internal_handler.Attendee'
        minItems: 1
        type: array
      contribution_role:
        type: string
      customer_email:
        type: string
      customer_name:
        type: string
      customer_phone:
        type: string
      profile_age:
        description: Menggantikan field survei dengan Profile
        type: string
      profile_city:
        type: string
      profile_education:
        type: string
      profile_job:
        type: string
      profile_motivation:
        type: string
      ticket_type:
        type: string
      voucher_code:
        type: string
    required:
    - attendees
    - customer_email
    - customer_name
    - customer_phone
    - ticket_type
    type: object
  internal_handler.CreateUserInput:
    properties:
      password:
        type: string
      role:
        description: admin / scanner
        type: string
      username:
        type: string
    required:
    - password
    - role
    - username
    type: object
  internal_handler.CreateVoucherInput:
    properties:
      code:
        type: string
      discount_amount:
        type: number
      quota:
        type: integer
    required:
    - code
    - discount_amount
    - quota
    type: object
  internal_handler.LoginInput:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  internal_handler.UpdateVoucherInput:
    properties:
      discount_amount:
        type: number
      quota:
        type: integer
    required:
    - discount_amount
    - quota
    type: object
  internal_handler.VerifyPaymentInput:
    properties:
      action:
        enum:
        - approve
        - reject
        type: string
    required:
    - action
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API Documentation for SMILE FEST 2026 Ticketing System.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: SMILE FEST API
  version: "1.0"
paths:
  /api/admin/dashboard:
    get:
      description: Mengambil agregasi data pendapatan dan penjualan tiket (Real-time)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get Dashboard Statistics
      tags:
      - admin
  /api/admin/ticket-variants/{id}:
    put:
      description: Admin membuka atau menutup penjualan fase tiket secara manual (Kill
        switch)
      parameters:
      - description: Variant ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Toggle Ticket Variant Status
      tags:
      - admin
  /api/admin/transactions:
    get:
      description: Melihat daftar riwayat transaksi peserta.
      parameters:
      - description: Cari nama / email
        in: query
        name: search
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get All Transactions
      tags:
      - admin
  /api/admin/transactions/{id}/verify:
    put:
      consumes:
      - application/json
      description: Admin melakukan persetujuan (approve) atau penolakan (reject) terhadap
        bukti transfer peserta. Approve akan mengirimkan E-Ticket otomatis.
      parameters:
      - description: Order ID (Transaction ID)
        in: path
        name: id
        required: true
        type: string
      - description: Aksi Verifikasi (approve/reject)
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_handler.VerifyPaymentInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Verify Manual Payment
      tags:
      - admin
  /api/admin/users:
    get:
      description: Admin melihat daftar seluruh panitia dan admin yang terdaftar
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get All Users
      tags:
      - admin
    post:
      consumes:
      - application/json
      description: Hanya bisa diakses Admin untuk membuat akun Scanner/Admin baru
      parameters:
      - description: Data User Baru
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_handler.CreateUserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Create New User
      tags:
      - admin
  /api/admin/users/{id}:
    delete:
      description: Admin menghapus/mencabut akses akun panitia
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Delete User
      tags:
      - admin
  /api/admin/vouchers:
    get:
      description: Admin melihat daftar voucher dan sisa kuota
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get All Vouchers
      tags:
      - admin
    post:
      consumes:
      - application/json
      description: 'Admin menambah kode diskon baru (misal: PELAJAR20K)'
      parameters:
      - description: Data Voucher
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_handler.CreateVoucherInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Create New Voucher
      tags:
      - admin
  /api/admin/vouchers/{id}:
    delete:
      description: Admin menghapus voucher secara permanen
      parameters:
      - description: Voucher ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Delete Voucher
      tags:
      - admin
    put:
      consumes:
      - application/json
      description: Admin merubah potongan harga atau kuota voucher
      parameters:
      - description: Voucher ID
        in: path
        name: id
        required: true
        type: integer
      - description: Data Update Voucher
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_handler.UpdateVoucherInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update Voucher
      tags:
      - admin
  /api/admin/vouchers/{id}/toggle:
    put:
      description: Admin mematikan (Kill Switch) atau menyalakan kembali voucher
      parameters:
      - description: Voucher ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Toggle Voucher Status
      tags:
      - admin
  /api/checkout:
    post:
      consumes:
      - application/json
      description: Membuat transaksi dengan kode unik dan auto-batching sesi, reservasi
        tiket selama 24 jam. Mengirim email intruksi pembayaran dengan goroutine.
      parameters:
      - description: Data Pembeli dan Daftar Pemegang Tiket
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_handler.CheckoutInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Create Transaction Checkout (Manual Transfer)
      tags:
      - public
  /api/login:
    post:
      consumes:
      - application/json
      description: Mendapatkan JWT token untuk akses API
      parameters:
      - description: Kredensial Login
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_handler.LoginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: User Login
      tags:
      - auth
  /api/scanner/stats:
    get:
      description: Panitia lapangan melihat jumlah peserta yang sudah masuk
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get Scanner Stats
      tags:
      - scanner
  /api/scanner/validate-ticket:
    post:
      consumes:
      - application/json
      description: Memvalidasi QR Code dari tiket peserta di hari H
      parameters:
      - description: Ticket UUID
        in: body
        name: input
        required: true
        schema:
          additionalProperties:
            type: string
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Validate Ticket
      tags:
      - scanner
  /api/seed-admin:
    post:
      description: Temporer untuk membuat akun admin pertama (Matikan rute ini setelah
        dipakai)
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Seed First Admin
      tags:
      - auth
  /api/tickets/info:
    get:
      description: Mengambil data harga dan tipe tiket yang sedang aktif berdasarkan
        periode tanggal hari ini
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Get Ticket Info
      tags:
      - public
  /api/tickets/track:
    get:
      description: Peserta mencari tiket mereka, mengecek status verifikasi admin,
        atau melihat instruksi pembayaran manual (jika status masih pending).
      parameters:
      - description: Order ID (SMILE-xxx)
        in: query
        name: order_id
        required: true
        type: string
      - description: Email Peserta
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Track E-Ticket & Payment Status
      tags:
      - public
  /api/transactions/{id}/upload-proof:
    post:
      consumes:
      - multipart/form-data
      description: Mengunggah gambar bukti transfer untuk transaksi tertentu
      parameters:
      - description: Order ID
        in: path
        name: id
        required: true
        type: string
      - description: File Gambar Bukti Transfer (Max 2MB)
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Upload Payment Proof
      tags:
      - public
  /api/vouchers/validate:
    get:
      description: Peserta mengecek apakah voucher valid dan kuota masih ada sebelum
        checkout
      parameters:
      - description: Kode Voucher
        in: query
        name: code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Validate Voucher Code
      tags:
      - public
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
